Add Dockerfile and Docker commands to PoshC2 - check the README for instructions

diff --git a/Files/posh-update b/Files/posh-update
--- a/Files/posh-update
+++ b/Files/posh-update
@@ -32,11 +32,28 @@ if [ "$?" -eq "0" ]; then
     echo ""
 
     echo ""
-    echo "[+] Performing git pull on $ROOTDIR"
-    git pull --rebase
+    echo "[+] Saving changes to Config.py"
+    echo ""
+    git diff Config.py >> /tmp/PoshC2_Config_Diff.git
 
+    echo ""
+    echo "[+] Updating Posh Installation to latest master"
+    git fetch
+    git reset --hard origin/master
+
+    echo ""
     echo "[+] Running Install script"
     ./Install.sh
+
+    echo ""
+    echo "[+] Re-applying Config file changes"
+    git apply /tmp/PoshC2_Config_Diff.git
+
+    if [ "$?" -eq "0" ]; then
+        rm /tmp/PoshC2_Config_Diff.git
+    else
+        echo "[-] Re-applying Config file changes failed, please merge manually from /tmp/PoshC2_Config_Diff.git"
+    fi
 
     echo ""
     echo "[+] Update complete"
