Add Dockerfile and Docker commands to PoshC2 - check the README for instructions

diff --git a/Files/posh-log b/Files/posh-log
--- a/Files/posh-log
+++ b/Files/posh-log
@@ -1,5 +1,13 @@
 #!/bin/bash
 
-tail -n 500 -f /var/log/poshc2_server.log 2>/dev/null\
-	|| ( echo -e "\e[31m[!] Could not open logfile: /var/log/poshc2_server.log\e[0m")
+if [[ -z "${POSHC2_DIR}" ]]; then
+    POSH_DIR="/opt/PoshC2"
+else
+    POSH_DIR=${POSHC2_DIR} 
+fi
+
+POSH_PROJECT_DIR=`cat $POSH_DIR/Config.py | grep "ROOTDIR = " | cut -d "\"" -f 2`
+
+tail -n 5000 -f "$POSH_PROJECT_DIR/poshc2_server.log" 2>/dev/null\
+	|| ( echo -e "\e[31m[!] Could not open logfile: "$POSH_PROJECT_DIR/poshc2_server.log"\e[0m")
 
